#!/usr/bin/env bash

eDP1="--output eDP-1 --primary --scale 0.75x0.75 --mode 3840x2400 --pos 0x900 --rotate normal"
eDP1HOME="--output eDP-1 --primary --scale 0.75x0.75 --mode 3840x2400 --pos 0x700 --rotate normal"
DP1="--output DP-1 --scale 1.25x1.25 --mode 3840x2160 --pos 2880x0 --rotate normal"
DP1OFF="--output DP-1 --off"
HDMI1="--output HDMI-1 --scale 1.5x1.5 --mode 2560x1440 --pos 2380x0 --rotate normal"
HDMI1OFF="--output HDMI-1 --off"
# DP2OFF="--output DP-2 --off"
# DP3OFF="--output DP-3 --off"
# DP4OFF="--output DP-4 --off"

xrandr $eDP1

if xrandr | grep -q "DP-1 disconnected"; then
    echo "External monitor not connected"
    xrandr $DP1OFF
else 
    echo "External monitor connected"
    xrandr --output DP1 --auto
    xrandr $DP1
fi

if xrandr | grep -q "HDMI-1 disconnected"; then
    echo "External monitor not connected"
    xrandr $HDMI1OFF
else
    echo "External monitor connected"
    xrandr --output $HDMI --auto
    xrandr $HDMI1
fi

xrandr $eDP1HOME