#!/usr/bin/env python3

import subprocess

def main():
    try:
        #  kubectl auth can-i list pods --namespace=default

        result = subprocess.run(["kubectl","get", "namespaces"], capture_output=True, text=True, check=True)
        output = result.stdout
        color = "#ffffff" if "Active" in output else "#ff0000"

        # Print the results for i3blocks
        print("k8s")
        print("k8s")
        print(color)
    except:
        print("k8s")
        print("k8s")
        print("#ff0000")

if __name__ == "__main__":
    main()