#!/usr/bin/env python3

import subprocess

def main():
    try:
        result = subprocess.run(['globalprotect',"show", "--status"], capture_output=True, text=True, check=True)
        output = result.stdout
        color = "#ffffff" if "GlobalProtect status: Connected" in output or "already established" else "#ff0000"

        # Print the results for i3blocks
        print("VPN")
        print("VPN")
        print(color)
    except:
        print("VPN")
        print("VPN")
        print("#ff0000")

if __name__ == "__main__":
    main()